### PR TITLE
Fix flip aug

### PR DESCRIPTION
**Pull request by simonJJJ**
It's a bug that it will never flip the boxes, but has a chance to flip the image.

### CODE REVIEW

**Comment by KaihuaTang** [comment]
The reason I don't flip the image is that I'm afraid that flipping the image will change some spatial relationship in Scene Graph Generation, e.g., in some GQA dataset, there are 'to the left' / 'to the right' relationships.

**Comment by simonJJJ** [comment]
My concern is that there is a chance to flip the image but not flip the bbox. You could always set flip_aug to False but still need to fix the wrong argument passing in get_groundtruth func.

**Comment by yangzhaopeng3** [comment]
I check the code and notice that when building transformations, the `flip_horizontal_prob = 0.5`
https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch/blob/d0ffa40d92133d7d865e531146de82c8c8a344c0/maskrcnn_benchmark/data/transforms/build.py#L9
which means that the images have a probability of 0.5 to flip horizontally.
While the `FLIP_AUG: False` means that the bboxes won't flip even the images are flipped. Is this a bug or I miss something else?

**Comment by KaihuaTang** [comment]
yes, it's a bug

**Comment by simonJJJ** [comment]
Did I miss something?

**Comment by KaihuaTang** [comment]
Never mind. I was going to reply to another issue. I commented on this issue by mistake.

**Pull request closed without merging**
