### PR TITLE
SGDet Visualization

### PR DESCRIPTION
**Pull request by navidre**
Issue #2.

### CODE REVIEW

**Comment by koihoo** [comment]
hello ,thank your code!
but i got the bug ,can you help me ?
image

**Comment by koihoo** [comment]
@navidre  I'm looking forward to hearing from you!!!!

**Comment by navidre** [comment]
Hey @koihoo, I will try to replicate and will get back to you later. Thanks, Navid

**Comment by GalaxDust** [comment]
Hello,
I encountered an Out-Of-Memory (OOM) issue in the final stages of running the SGDet training script, likely due to hardware limitations. When using the author's visualization script and executing the following code:
`detected_origin_path = '/root/autodl-tmp/checkpoints/relation_motif_SGDet/inference/VG_stanford_filtered_with_attribute_test/'
detected_origin_result = torch.load(detected_origin_path + 'eval_results.pytorch')
detected_info = json.load(open(detected_origin_path + 'visual_info.json'))`
I am unable to load the visual_info.json file. Could anyone provide the files from the trained VG_stanford_filtered_with_attribute_test directory? Your help would be greatly appreciated.

Thank you!

**Pull request merged**
